name: Bump Homebrew formula

on:
  push:
    tags: '*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: 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
          tap: metis-data/homebrew-cli-brew
          formula: MetisCli
